alphagov/info-frontend

app/controllers/info_controller.rb
spec/features/info_spec.rb

Before this change, slugs that needed encoding (eg /info/""<--) raised exceptions. Such
slugs can be requested by malicious attempts or when a user mistypes the URL.

Handle slugs that need encoding

---

app/controllers/application_controller.rb
app/views/layouts/application.html.erb

Use the govuk_component alpha label rather than the slimmer inserted
one. This will let us iterate the design in a faster more consistent
way.
This will need static to be deployed before this as the alpha-label isn't on production yet.

Use govuk_components rather than slimmer inserter

---

spec/support/metadata_api_helpers.rb

These fields no longer appear in Need API and have also been
[removed from Metadata API](https://github.com/alphagov/metadata-api/pull/15).

Remove deprecated Metadata API fields

---

app/controllers/info_controller.rb
app/views/info/_artefact.html.erb
app/views/info/_needs.html.erb
app/views/info/show.html.erb
config/application.rb
config/initializers/show_needs.rb
spec/features/info_spec.rb
spec/support/metadata_api_helpers.rb

This change simplifies the decision of whether to display a need or not.
After this change, the need is show if it's valid, and hidden if it's not.
Before this is released to production, it's necessary to merge [the deployment config change](https://github.gds/gds/alphagov-deployment/pull/863).

Only show validated needs

---

app/views/info/_lead_metrics.html.erb

Make it easy to see the type of search results users are seeing when they leave a page using a common search term.
cc @benilovj @rboulton

Link searches to search results

---

app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/info/_artefact.html.erb
app/views/layouts/application.html.erb

Modernise this frontend to use the standard Slimmer Template layout, and make use of all components.
All changes visually diffed with `wraith`, the only regression being the expected from from the title component change (see below).
**Switch slimmer template to 'core_layout'**
`core_layout` is the default layout since Slimmer 9.0.0 [1], and apps
should be using it where possible.
The advantage over `header_footer_only` is that `core_layout` sets a
base grid/container for the main content, so apps don't need to
replicate it each time.
This switches the layout, but not overriding the default, and removes
the grid/container code specific to this app.
The SASS `grid_layout` isn't needed, but was including `measurements`
which is relied on else where.
[1] alphagov/slimmer#136
**Use 'title' …

Use core layout & title component

---

Rakefile

This stops deployments breaking, as they try to precompile the assets,
and fail on loading this.

Only require 'ci/reporter/rake/rspec' in the useful environments

---

config/initializers/airbrake.rb

This file was copied across from the Publishing API, but that project
uses a different version of airbrake.

Fix airbrake config

---

config/environments/development.rb

Use GOVUK_ASSET_HOST as is used in the production environment, and add
it to the development environment as its useful for development.

Configure asset_host in development

---

app/views/info/show.html.erb

It was accidentally moved below the metrics.

Restore the content partial to the top of the page

---

app/controllers/info_controller.rb

Multi-part content (e.g. guides) no longer appear to have a web_url in
the parts when fetched from the Content Stores. Instead the part urls
can be constructed from the slug of the part.
I've deployed this to integration, as I don't have the metadata-api locally to test with, and it seems to work.

Change extracting part urls from the details of content

---

Gemfile
Gemfile.lock
app/controllers/info_controller.rb
lib/govuk/client/metadata_api.rb

Use gds-api-adapters to handle JSON responses and errors from the metadata API. This means that the deprecated govuk-client-url_arbiter gem can be retired.
https://trello.com/c/u1H1rgDA/525-some-finding-pages-are-still-being-tracked-as-thing

Replace usages of govuk-client-url_arbiter with gds-api-adapters

---

app/controllers/info_controller.rb
spec/features/info_spec.rb
spec/support/metadata_api_helpers.rb

[`govuk_content_api`](https://github.com/alphagov/govuk_content_api)
has been deprecated, and is being removed from the Metadata API
(https://github.com/alphagov/metadata-api/pull/35).
Since Metadata API will no longer attempt to fetch content from the
Content API, then we no longer need to fall back to the Metadata API.
https://trello.com/c/o1TJIoUq/77-make-metadata-api-thus-info-frontend-no-longer-request-from-content-api

Remove Metadata API fallback

---

spec/features/info_spec.rb

This is a new field which is going to be added to the Content Store, but it won't appear in the links hash, so we need to exclude it as we have done with the others.
[Trello Card](https://trello.com/c/JZ5Zabe9/702-remove-publishing-request-id-from-travel-advice-publisher-details-hash-2)

Exclude publishing_request_id field from tests

---

app/controllers/info_controller.rb

This avoids erroring when the content store returns HTTP Gone.

Return 404 when the item can't be retrived from the content store

---

Gemfile
Gemfile.lock
lib/performance_data/statistics.rb
lib/performance_data/test_helpers/statistics.rb

For: https://trello.com/c/9JNitfXS/173-spike-info-pages
As part of the process to replace `metadata-api` in `info-frontend`, we're now using 4 new API calls in `gds-api-adapters` in order to talk to the `backdrop read API`. 
This used to be handled by `metadata-api`. 
However, the url path we were using for the performance endpoint was the non-secure version.
This commit replaces the performance url with the SSL enabled version (`http` -> `https`)
It also removes the `PP_DATA_OUT_ENDPOINT` from `test_helpers/statistics.rb` since it's not being used.

Uses SSL version of performance URL

---

lib/performance_data/statistics.rb
spec/models/performance_data/lead_metrics_spec.rb
spec/models/performance_data/statistics_spec.rb
spec/support/statistics_helpers.rb

This is a follow up to https://github.com/alphagov/info-frontend/pull/71 and https://github.com/alphagov/info-frontend/pull/72 where we are in the process of removing metadata-api from info-frontend.
In order to do this, we have moved the api calls handled by `metadata-api` into `gds-api-adapters`. The api calls will be passed on by `gds-api-adapters` to the `backend read api`. The response is parsed and rendered by `info-frontend`.
This commit will take into account the possibility that the response we receive from `backend read API` contains `nil` in the `value` param. This was a use case that was not taken into account before, so there is now a test to check that we can handle it.
Previously, the formatting of nil values was handled by `metadata-api` in here: …

Formats nil values for performance stats

---

app/controllers/info_controller.rb
lib/performance_data/statistics.rb
spec/features/info_spec.rb
spec/models/performance_data/statistics_spec.rb

The statistics class was introduced to take over the duties from metadata-api: fetch data from the performance platform and format the data. However, it wasn't being strict about checking whether the page we're fetching performance data for has their slug starting with a "/".
It's not longer assuming the data it's receiving is correct and always makes sure to add the forward slash to the slug before sending the request to the performance platform.
The missing slash meant that for multi-part pages, the data would not be fetched correctly.
Initial transition from metadata-api to just using the `Statistics` class in `info-frontend` was carried out for: https://trello.com/c/9JNitfXS/173-spike-info-pages

Format performance slug before doing request

---

app/views/layouts/application.html.erb

For: https://trello.com/c/nVb1OsNd/144-enable-subresource-integrity-sri-on-info-frontend-s
There's only one stylesheet to add them to, all other assets come from static, which we've not added SRI to yet.

Add SRI attributes

---

app/controllers/info_controller.rb
app/views/info/_lead_metrics.html.erb
app/views/info/_needs.html.erb
app/views/info/show.html.erb
lib/performance_data/statistics.rb
lib/performance_data/test_helpers/statistics.rb
spec/models/performance_data/statistics_spec.rb
spec/views/info/_lead_metrics.html.erb_spec.rb

For: [Trelllo card](https://trello.com/c/oVwtZ40Z/197-improve-use-of-statistics-in-info-frontend)
Following the [removal of metadata-api](https://github.com/alphagov/info-frontend/pull/71), the `info-frontend` code introduced to replace it can stand to get some improvements to reduce indirection and remove redundancy. 
This will make the code more readable and will help us when we attempt to speed up the 4 api requests being done to the performance platform (which was previously handled by `metadata-api`).

Improvements to statistics

---

spec/features/info_spec.rb
spec/models/performance_data/statistics_spec.rb

This field has now been replaced by the `meets_user_needs` link type.

Remove code related to need_ids

---

app/controllers/info_controller.rb
app/views/info/show.html.erb

This `rescue` causes `@statistics` to be nil and the view to crash eventually, but without an informative message in Sentry. This will at least give us the actual error in Sentry.

Remove shonky error handling

---

app/controllers/application_controller.rb
app/views/info/_content.html.erb
app/views/layouts/application.html.erb
spec/support/slimmer.rb

This uses the title and phase banner component from the gem rather than static. Because we're no longer using Static-based components this also removes the Slimmer helpers.
https://trello.com/c/qtXCDGQI

Use gem based components

---

spec/features/info_spec.rb
spec/models/performance_data/statistics_spec.rb

Trello: https://trello.com/c/uR7v1Rri
The changes introduced in https://github.com/alphagov/govuk-content-schemas/pull/891
are causing the info-frontend schema tests to fail.
These changes remove the `links` hash from the random examples completely and allow them to be
overwritten in the tests.
See:
https://ci.integration.publishing.service.gov.uk/job/info-frontend/job/deployed-to-production/119/

Exclude `links` from payload in schema tests

---

.rubocop.yml
Gemfile
Gemfile.lock

- The GOV.UK Lint gem is deprecated in favour of using Rubocop directly
with a set of shared configs.
- See https://github.com/alphagov/govuk-rfcs/pull/ 100 for more context.
https://trello.com/c/CdBFg6yw/1521-replace-govuk-lint-with-rubocop-govuk

Replace govuk-lint

---

app/assets/stylesheets/application.scss

Reduce the filesize of the compiled CSS by importing only the styles for components in use.
**Before**
**After**
**Sample urls**
https://govuk-info-f-import-ind-ehrqzb.herokuapp.com/info/disability-living-allowance-children
https://govuk-info-f-import-ind-ehrqzb.herokuapp.com/info/guidance/pupil-premium-information-for-schools-and-alternative-provision-settings
https://govuk-info-f-import-ind-ehrqzb.herokuapp.com/info/register-to-vote

Import individual sass files instead of all

---

spec/features/info_spec.rb

Replace instances of content_store_has_item with stub_content_store_has_item in the tests in line with the deprecation message: `content_store_has_item is deprecated on GdsApi::TestHelpers::ContentStore and will be removed in a future version. Use #stub_content_store_has_item instead`

Fix deprecation messages for content_store stubs

---

config/environments/production.rb

During the rails migration this line was added to the production config: `ActiveRecord::Middleware::DatabaseSelector::Resolver::Session`, this causes the deploy to fail since the application does not use its own database. Here we have commented it out again (as it was generated in the rails 6 upgrade).
Trello ticket: https://trello.com/c/0d6k3UdH/1798-5-upgrade-info-frontend-to-rails-6#comment-5e6794e41f9f4e5f9d34f079

Remove ActiveRecord setup in production config

---

Gemfile
Gemfile.lock
app/controllers/info_controller.rb

Upgrade to Ruby `2.7.1` and fix the warning `URI.escape is obsolete`

Upgrade to Ruby 2.7.1

---

.github/pull_request_template.md

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
This is part of enabling automatic deployments for this app.
:warning: This application is Continuously Deployed: :warning:
- Merged changes are automatically deployed to staging and production.
- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) **before** you merge.
- Check your branch is being deployed in the [Release app](https://release.publishing.service.gov.uk/applications/smartanswers), after merging.
- Changes to start pages are **not** continuously deployed, and are [deployed using a different process](https://github.com/alphagov/smart-answers/blob/master/doc/smart-answer-flow-development/pu …

Add PR template before enabling automatic deploys

---

app/controllers/info_controller.rb
app/views/info/show.html.erb
spec/features/info_spec.rb

The performance platform API has been decommissioned.
None of the statistics that used to come from performance platform will work anymore.
User needs from Maslow are still okay though :tada: 
For now, I'm just commenting out the places where we called the performance platform's API.
If we want this functionality back we could look at pulling it directly from Google Analytics, or from Search or from Content Data.
https://trello.com/c/DVnwOgMg/2090-performance-platform-retirement-handle-info-pages

Disable performance platform

---

lib/tasks/publishing_api.rake
spec/lib/tasks/publishing_api_spec.rb
spec/rails_helper.rb

Replace defunct use of PublishingApiV2 in rake task
GdsApi no longer exports PublishingApiV2, so this rake task has been broken for a while. No biggy because it never had any tests, and we don't run it regularly. Still probably worth fixing (or removing?).

Fix publish special routes rake task

---

app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/layouts/application.html.erb

Update `info-frontend` to use the Design System-based page layout and turn on the `govuk-new-link-styles` flag.
Major benefits include performance improvements, accessibility improvements, and consistency with other applications.
No visual changes.

Swap to `gem_layout` and adopt new link styles

---

app/controllers/application_controller.rb
app/controllers/info_controller.rb
spec/features/info_spec.rb

Content Store provides a TTL in the Cache-Control response header which frontend apps should respect.
This ensures that Info-frontend honours the cache TTL provided by Content Store.
This partially implements RFC 144.
Links:
* Content Store TTL: https://github.com/alphagov/content-store/blob/9661e2047f2167f87066fbb6ef38da71668a1327/app/controllers/content_items_controller.rb#L14
* RFC 144: https://github.com/alphagov/govuk-rfcs/blob/main/rfc-144-consistent-cache-expiry.md
https://trello.com/c/OaUhq6uI/722-replatform-emergency-banner

Respect Content Store TTL

---

Dockerfile
config/puma.rb

Adding a Dockerfile so that info-frontend can be migrated to the EKS platform. 
Adding a puma config file so that puma is used as the web server.

Adding Dockerfile

---

.github/workflows/ci.yaml

Uses a shared workflow hosted in govuk-infrastructure repo (as implemented in https://github.com/alphagov/.github/tree/main/workflow-templates)
Implements a reusable workflow: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
This is only possible since the infrastructure repo is public.

Use shared workflow

---

config/application.rb

This allows asset host to be set by ASSET_HOST env var as it looks like the assets of this app changed hostname from
assets.publishing.service.gov.uk to www.gov.uk as outlined in [RFC 115][rfc-115].
[rfc-115]: https://github.com/alphagov/govuk-rfcs/blob/master/rfc-115-enabling-http2-on-govuk.md
As part of this change the path to assets is changed to `/assets/info-frontend`
This should fix the JS errors in staging flagged by [Smokey](https://deploy.blue.staging.govuk.digital/job/Smokey/19922/console) during deploy (tested by deploying a branch to staging).
<kbd><img width="790" alt="Screenshot 2022-07-13 at 16 30 28" src="https://user-images.githubusercontent.com/38078064/178772928-69839064-4970-45db-af86-2f197eb2927d.png"></kbd>
⚠️ This repo is Continuously Deployed: make sure you [follow …

Switch asset host env var for change of asset host

---

Dockerfile

Updates the Dockerfile to use the new [GOV.UK Ruby base images](https://github.com/alphagov/govuk-ruby-images).
Context: https://trello.com/c/Zy0fd25w/970-use-base-builder-images-in-all-the-app-dockerfiles

Update Dockerfile to use GOV.UK Ruby base images 

---

app.json

See alphagov/gds-api-adapters#1170.

Fix environment variable name for Search API backend.

---

Dockerfile

This was missed when updating the .ruby-version

Update the ruby version in the Dockerfile

---

Procfile
config/unicorn.rb

Unicorn has been replaced by Puma as the web server so the config can be removed.
See: https://github.com/alphagov/govuk_app_config/commit/71f4f2fa3871721e5c8140bcf73d683e09d8d7b2

Remove unicorn config

---

app/views/layouts/application.html.erb

Remove options passed to components for enabling GA4 tracking. All components referenced now have tracking enabled by default, and this option has been removed.
Unneeded code.
None.
Trello card: https://trello.com/c/Xwp7dgJN/294-tracking-auditing-tracking-by-default

Remove unneeded instances of ga4_tracking: true

---

.govuk_dependabot_merger.yml

Allow the govuk-dependabot-merger to merge minor and patch versions of internal govuk gems for Collections, Frontend, Government-frontend and Info-frontend
To reduce dev TOIL
[Trello ticket](https://trello.com/c/XEH7rn6w/2320-configure-govuk-dependabot-merger-for-our-applications-s)

Configure govuk-dependabot-merger

---

docs/adr/retiring-info-frontend.md

This has already been agreed by the various stakeholders on gov.uk but transferring the doc to the app repo seems sensible + it's easier to share than a Google doc.
Rendered: https://github.com/alphagov/info-frontend/blob/6dae8deb879ede15bced3f632e0f1a856257b78a/docs/adr/retiring-info-frontend.md
Original doc: https://docs.google.com/document/d/1uk07QWQqWrI_oOJfkfvQnbwwp57nnyvZWRo8dX5xGRs/edit

Adds retiring Info Frontend ADR

---

docs/adr/retiring-info-frontend.md

We're now unpublishing info pages with a 410 gone vs single content page.

Update retiring info frontend ADR
